

name: idm - xr66

env:
  IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  IBM_CF_APP_MEM: 128M

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 22 * * 9

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IBM_CF_USERNAME: ${{ secrets.IBM_CF_USERNAME }}
      IBM_CF_PASSWORD: ${{ secrets.IBM_CF_PASSWORD }}
      IBM_CF_ORG_NAME: ${{ secrets.IBM_CF_ORG_NAME }}
      IBM_CF_SPACE_NAME: ${{ secrets.IBM_CF_SPACE_NAME }}
      IBM_CF_APP_NAME: ${{ secrets.IBM_CF_APP_NAME }}
      V2_UUID: ${{ secrets.V2_UUID }}
      V2_WS_PATH_VMESS: ${{ secrets.V2_WS_PATH_VMESS }}
      V2_WS_PATH_VLESS: ${{ secrets.V2_WS_PATH_VLESS }}

    steps:

    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zxC /tmp
        sudo install -m 755 /tmp/cf7 /usr/local/bin/cf
        cf version

    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
          -a "${IBM_CF_API}" \
          -u "${IBM_CF_USERNAME}" \
          -p "${IBM_CF_PASSWORD}" \
          -o "${IBM_CF_ORG_NAME:-$IBM_CF_USERNAME}" \
          -s "${IBM_CF_SPACE_NAME:-dev}"

    - name: Download Latest xr66
      run: |
        DOWNLOAD_URL="https://d.5968.cf/d/Onedrive-a@peiqi6/admin/xr66/xr66.zip?pw=0a44c75e75386857"
        curl -fsSL "$DOWNLOAD_URL" -o "xr66.zip"
        unzip xr66.zip xr66 geoip.dat geosite.dat
        rm xr66.zip
        chmod -v 755 xr*
        ./xr66 -version
        mv xr66 ${IBM_CF_APP_NAME}

    - name: Generate xr66 Config File (VMess)
      if: ${{ env.V2_WS_PATH_VMESS }}
      run: |
        base64 << xr66 > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${V2_UUID}",
                    "alterId": 0
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${V2_WS_PATH_VMESS}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        xr66

    - name: Generate xr66 Config File (VLESS)
      if: ${{ env.V2_WS_PATH_VLESS }}
      run: |
        base64 << xr66 > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vless",
              "settings": {
                "decryption": "none",
                "clients": [
                  {
                    "id": "${V2_UUID}"
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${V2_WS_PATH_VLESS}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        xr66

    - name: Generate Manifest File
      run: |
        cat << xr66 > manifest.yml
        applications:
        - name: ${IBM_CF_APP_NAME}
          memory: ${IBM_CF_APP_MEM}
          random-route: true
          command: base64 -d config > config.json; ./${IBM_CF_APP_NAME} -config=config.json
          buildpacks:
          - binary_buildpack
        xr66

    - name: Deploy Cloud Foundry App
      run: cf push
